# -*- coding: utf-8 -*-
"""Solucion_caso_practico_IEP_IAA_NLP_u1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z_bo18F5xw9zfx1jfJzZGR7QSBIQgZMM

## Preguntas Críticas – Unidad 2: Pipeline de NLP

A continuación, presentamos una serie de preguntas reflexivas para profundizar en los conceptos aprendidos sobre el pipeline de procesamiento de lenguaje natural:

### 1. Importancia de las Etapas
- ¿Cuál es la importancia de cada etapa del pipeline de NLP (preprocesamiento, modelado, postprocesamiento y evaluación)?
- ¿Cómo influyen estas etapas en la calidad de los resultados finales?

### 2. Preprocesamiento de Texto
- ¿Qué técnicas de preprocesamiento son más efectivas para preparar datos textuales para el modelado en NLP?
- ¿Qué problemas pueden surgir durante el preprocesamiento y cómo se pueden evitar?

### 3. Modelado en NLP
- ¿Cuáles son algunos de los enfoques más comunes para el modelado en NLP y qué ventajas y desventajas tiene cada uno?
- ¿Cómo se puede seleccionar el enfoque más adecuado para un problema específico?

### 4. Evaluación del Modelo
- ¿Qué métodos de evaluación se pueden usar para medir el rendimiento de un modelo de NLP?
- ¿Cómo se puede garantizar una evaluación justa y precisa?
- ¿Qué métricas se deben considerar para obtener una evaluación integral?

### 5. Evaluación Cualitativa
- ¿En qué tareas es crucial una evaluación cualitativa (ej. generación de texto, traducción automática)?
- ¿Qué aspectos analiza esta evaluación que no capturan las métricas cuantitativas?

---

*Reflexionar sobre estas preguntas permitirá una mejor comprensión del ciclo completo de un proyecto de NLP y ayudará a desarrollar soluciones más robustas y responsables.*

# Caso Práctico – Pipeline de NLP: Análisis de Reseñas de Productos

## Objetivo
El objetivo de este caso práctico es construir un pipeline de procesamiento de lenguaje natural (NLP) completo que nos permita analizar reseñas de productos (dataset de Amazon). Seguiremos las etapas típicas del pipeline:

- **Preprocesamiento de texto**: Limpieza, tokenización, eliminación de stopwords y lematización.
- **Modelado**: Clasificación de las reseñas como positivas o negativas usando modelos de Machine Learning.
- **Evaluación**: Medición del rendimiento del modelo con métricas cuantitativas como precisión, recall y F1-score.

## Herramientas y Librerías
- `pandas`: Manipulación de datos.
- `nltk`: Preprocesamiento de texto (tokenización, stopwords, lematización).
- `sklearn`: Construcción del modelo de clasificación y evaluación del rendimiento.
- `Google Colab`: Entorno de ejecución recomendado.

## Dataset
Trabajaremos con reseñas reales del archivo `amazon_reviews.csv`, disponible en:

> *Este ejercicio me permitirá aplicar de forma práctica los conocimientos aprendidos sobre pipelines de NLP y reflexionar sobre su impacto en la calidad del modelo final.*
"""

# Librerías necesarias
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# 🔄 Descargar recursos de NLTK (si no se han descargado)
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

# Cargar el dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/datos_IEP_IAA_NLP_u1/Unidad 1/amazon_reviews.csv')

# Ver un resumen del dataset
df.head()

# Reemplazo de word_tokenize por .split()
# Esta solución evita el uso de 'punkt' por completo

import nltk
import re
import pandas as pd
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Descargar solo lo necesario
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

# Función de preprocesamiento alternativa sin word_tokenize
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'<[^>]+>', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    tokens = text.split()  # ← reemplazo de nltk.word_tokenize
    stop_words = set(stopwords.words('english'))
    tokens = [t for t in tokens if t not in stop_words]
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(t) for t in tokens]
    return " ".join(tokens)

# Aplicar preprocesamiento
df['processed_review'] = df['reviewText'].astype(str).apply(preprocess_text)

# Mostrar resultados
df[['reviewText', 'processed_review']].head()

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

# Definir vectorizador TF-IDF
vectorizer = TfidfVectorizer(max_features=5000)

# Aplicar al texto preprocesado
X = vectorizer.fit_transform(df['processed_review'])

# Etiqueta de clasificación (puedes usar 'overall' o binarizarla si quieres sentimiento)
y = df['overall']

# Dividir en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

# Modelo
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

# Predicciones
y_pred = clf.predict(X_test)

# Evaluación
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

"""# **Resumen de Preprocesamiento, Vectorización y Modelado de Clasificación con Random Forest**

# 1. Preprocesamiento de texto

Se aplicaron técnicas de limpieza y normalización al texto de las reseñas:

1. Conversión a minúsculas.

2. Eliminación de HTML y puntuación.

3. Tokenización con nltk.

4. Eliminación de stopwords (palabras vacías).

5. Lematización para reducir palabras a su forma base.

# nltk + regex + WordNetLemmatizer

# 2. Vectorización TF-IDF

Transformamos el texto limpio a una representación numérica mediante TfidfVectorizer, limitando a las 5.000 palabras más frecuentes. Esto nos permitió representar las reseñas como vectores dispersos que reflejan la importancia de cada palabra en el corpus.

# 3. Modelo de Clasificación con Random Forest

Se entrenó un modelo RandomForestClassifier para predecir la calificación (overall) de una reseña en una escala de 1 a 5 estrellas.

  División de los datos en conjunto de entrenamiento (80%) y prueba (20%).

  Métrica principal: accuracy (precisión general).

  Evaluación con classification_report.

# 4. Resultados

Accuracy general: 0.798 (aprox. 80%)

El modelo predijo casi exclusivamente la clase 5.0, lo que indica desequilibrio de clases severo en los datos.

Clases 2.0, 3.0 y 4.0 no fueron predichas correctamente (precision y recall = 0.0).

# **Conclusión**

Aunque el modelo muestra una alta precisión general, no generaliza bien a clases minoritarias. Es recomendable aplicar técnicas como:

Rebalanceo de clases (oversampling, undersampling).

Clasificación binaria (opinión positiva vs negativa).

Ajuste de hiperparámetros o modelos alternativos.

# **Visualización del desequilibrio de clases y Matriz de Confusión**
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Visualizar la distribución de clases
plt.figure(figsize=(8, 5))
sns.countplot(x='overall', data=df)
plt.title("Distribución de Clases (Calificaciones de Reseñas)")
plt.xlabel("Calificación")
plt.ylabel("Número de Reseñas")
plt.show()

"""La matriz de confusión permite visualizar los errores de predicción del modelo. Muestra cómo muchas clases se predijeron incorrectamente como 5.0."""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Calcular matriz de confusión
cm = confusion_matrix(y_test, y_pred)

# Etiquetas ordenadas (asegura que coincidan con las clases)
labels = sorted(y.unique())

# Mostrar la matriz con etiquetas
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
disp.plot(cmap='Blues', xticks_rotation=45)
plt.title("Matriz de Confusión - Random Forest")
plt.show()

"""## Conclusión del Caso Práctico – Pipeline de NLP (Amazon Reviews)

En este caso práctico, desarrollamos un pipeline completo de Procesamiento de Lenguaje Natural (NLP) aplicado a reseñas de productos de Amazon. Se llevaron a cabo las siguientes etapas clave:

- **Preprocesamiento del texto**: limpieza, tokenización, eliminación de stopwords y lematización, para reducir ruido y estandarizar el texto.
- **Vectorización**: se aplicó TF-IDF para representar las reseñas como vectores numéricos.
- **Modelado**: se utilizó un clasificador Random Forest para predecir la calificación (`overall`) de cada reseña.
- **Evaluación**: mediante métricas de rendimiento (`accuracy`, `precision`, `recall`, `f1-score`) y una matriz de confusión.

### Resultados observados:

- **Accuracy general**: aproximadamente 79.8%, lo cual indica una buena capacidad de predicción general.
- **Distribución de predicciones**: el modelo predice de forma casi exclusiva la clase 5.0, lo que refleja un fuerte **desbalance en el dataset**, donde las reseñas positivas son mayoría.
- **Matriz de confusión**: muestra que las clases 1.0 a 4.0 no son bien representadas, con casi todas las predicciones cayendo en la clase 5.0.

### Limitaciones:

- El modelo presenta **sesgo hacia la clase dominante** (5.0), lo cual es común en datasets desbalanceados.
- Algunas clases (2.0, 3.0, 4.0) tienen pocas muestras y no se predicen correctamente.
- El modelo no incorpora validación cruzada ni ajuste de hiperparámetros.

### Recomendaciones autocriticas para mi, para mejoras futuras:

1. Aplicar **técnicas de balanceo de clases** (submuestreo, sobremuestreo o SMOTE).
2. Explorar **clasificación binaria** (positivo vs negativo) o agrupación de clases.
3. Probar otros modelos (e.g., `LogisticRegression`, `XGBoost`, `NaiveBayes`) y hacer ajuste de hiperparámetros.
4. Implementar **evaluación cruzada (cross-validation)** para validar la robustez del modelo.
5. Explorar representaciones más avanzadas como **Word2Vec o embeddings con BERT**.

Este ejercicio demuestra cómo construir y evaluar un pipeline completo de NLP en un problema real, destacando la importancia del preprocesamiento, el balance de clases y la selección del modelo en el rendimiento final.

## Preguntas Críticas – Unidad 2: Pipeline de NLP

A continuación se presentan las respuestas razonadas a las preguntas clave planteadas al inicio del caso práctico, con base en la experiencia aplicada durante el desarrollo del pipeline de análisis de reseñas de productos.

---

### 1. Importancia de las Etapas

**¿Cuál es la importancia de cada etapa del pipeline de NLP?**

- **Preprocesamiento**: Transforma texto crudo en una representación estandarizada, eliminando ruido y ambigüedad. Esta etapa es crítica para el éxito del modelado.
- **Modelado**: Es el núcleo del pipeline, donde se extraen patrones y se generan predicciones a partir de los datos vectorizados.
- **Postprocesamiento**: Afina los resultados del modelo, permite su interpretación y prepara los outputs para consumo externo.
- **Evaluación**: Permite medir el rendimiento, identificar errores y guiar mejoras. Sin una evaluación sólida, no se puede confiar en los resultados.

**¿Cómo influyen estas etapas en la calidad de los resultados?**

Cada etapa actúa como un filtro: errores o negligencias en las primeras fases (como el preprocesamiento) se amplifican en el modelado y evaluación. Un pipeline sólido y bien definido mejora la generalización del modelo y reduce errores de interpretación o sesgo.

---

### 2. Preprocesamiento de Texto

**¿Qué técnicas son más efectivas?**

- **Tokenización**, **eliminación de stopwords**, **lematización** y **normalización** son fundamentales.
- TF-IDF funcionó como una buena técnica de vectorización en este ejercicio.

**¿Qué problemas pueden surgir y cómo evitarlos?**

- Palabras mal tokenizadas, ruido HTML o puntuación residual pueden alterar los vectores.
- Evitarlo requiere una limpieza rigurosa y validaciones en las funciones aplicadas (e.g., `.lower()`, regex bien definidas).

---

### 3. Modelado en NLP

**¿Qué enfoques son comunes y cuáles son sus pros/contras?**

- **Modelos clásicos**: `Naive Bayes`, `SVM`, `Random Forest`. Son rápidos y fáciles de interpretar, pero menos precisos para tareas semánticas complejas.
- **Modelos basados en embeddings**: `Word2Vec`, `GloVe`, `FastText`. Capturan relaciones semánticas, mejorando tareas como clasificación o similitud.
- **Transformers (BERT, GPT)**: Precisión muy alta en tareas complejas. Requieren más recursos y datos.

**¿Cómo seleccionar el mejor enfoque?**

Depende del objetivo, la cantidad de datos, el balance de clases y la necesidad de interpretabilidad. Para un problema simple como clasificación de reseñas, un modelo tradicional como `Random Forest` fue adecuado como primer paso.

---

### 4. Evaluación del Modelo

**¿Qué métodos se pueden usar?**

- **Métricas cuantitativas**: Accuracy, Precision, Recall, F1-Score, Matriz de Confusión.
- **Evaluación cruzada** (k-fold) para verificar robustez del modelo.

**¿Cómo garantizar una evaluación justa?**

- Asegurarse de que el dataset esté balanceado o aplicar técnicas para compensar desbalances.
- Usar múltiples métricas, no solo accuracy.

**¿Qué métricas considerar?**

- **F1-score** para tareas con clases desbalanceadas.
- **Recall y Precision** cuando los falsos positivos/negativos tienen diferente importancia.
- **Matriz de confusión** para entender el comportamiento del modelo por clase.

---

### 5. Evaluación Cualitativa

**¿En qué tareas es crítica?**

- Generación de texto (chatbots, resúmenes).
- Traducción automática.
- Clasificación sensible (opiniones, diagnóstico médico).

**¿Qué aspectos cubre que no capturan las métricas cuantitativas?**

- **Fluidez**, **coherencia**, **tono**, **intención** y **comprensión contextual**.
- Detecta errores sutiles o sesgos que pueden pasar desapercibidos en una métrica numérica.

---

**Reflexión Final**: Este caso práctico evidencia que el pipeline de NLP no solo es una estructura técnica, sino también un enfoque metodológico para construir soluciones robustas, éticas y adaptables. Invertir tiempo en cada etapa asegura resultados más confiables y alineados con los objetivos del negocio o investigación.
"""